{
  "openapi": "3.0.3",
  "info": {
    "title": "Aruskas API Documentation",
    "description": "Documentation for Aruskas",
    "version": "1.0.0",
    "contact": {
      "name": "Rikzan Fernanda",
      "email": "fernandarikzan@gmail.com",
      "url": "https://rikzanfernanda.netlify.app"
    }
  },
  "servers": [
    {
      "url": "http://localhost:8000",
      "description": "Development server"
    },
    {
      "url": "https://aruskas.savingid.my.id",
      "description": "Production server"
    }
  ],
  "paths": {
    "/api/register": {
      "post": {
        "summary": "Register user",
        "tags": [
          "Authentication"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "nama",
                  "email",
                  "password"
                ],
                "properties": {
                  "nama": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "pekerjaan": {
                    "type": "string"
                  },
                  "alamat": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "Bambang": {
                  "description": "Example body",
                  "value": {
                    "nama": "Bambang",
                    "email": "bambang@gmail.com",
                    "password": "bambang",
                    "pekerjaan": "Wiraswasta",
                    "alamat": "Pemalang"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Response success from register",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Bambang": {
                    "$ref": "#/components/examples/UserResponseExample"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/login": {
      "post": {
        "summary": "Login user",
        "tags": [
          "Authentication"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "email",
                  "password"
                ],
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "Bambang": {
                  "description": "Example request",
                  "value": {
                    "email": "bambang@gmail.com",
                    "password": "bambang"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Response after login",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Bambang": {
                    "value": {
                      "timestamp": "2022-05-31 23:12:00",
                      "result": [],
                      "status": 200,
                      "message": "Login successfully!",
                      "token": "hfbgbjskjfg...(JWT token)",
                      "token_type": "bearer",
                      "id": 1,
                      "nama": "Bambang",
                      "email": "bambang@gmail.com"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/forgot-password": {
      "post": {
        "summary": "Send email to get reset password token",
        "tags": [
          "Authentication"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "email"
                ],
                "properties": {
                  "email": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "Bambang": {
                  "value": {
                    "email": "bambang@gmail.com"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Bambang": {
                    "value": {
                      "timestamp": "2022-05-31 08:12:00",
                      "status": 200,
                      "message": "",
                      "result": {
                        "token": "QDyXfLhM5MkTZInDk5klfLnGQTuslYFA2aylqjN86o1s5FsBSvHqHGoPXT43fLfH"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/reset-password": {
      "post": {
        "summary": "Send new password",
        "tags": [
          "Authentication"
        ],
        "parameters": [
          {
            "name": "token",
            "in": "query",
            "required": true,
            "description": "Reset password token",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "password"
                ],
                "properties": {
                  "password": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "Bambang": {
                  "value": {
                    "password": "bambang"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Bambang": {
                    "value": {
                      "timestamp": "2022-05-31 08:12:00",
                      "status": 200,
                      "message": "Berhasil reset password",
                      "result": []
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/banks": {
      "get": {
        "summary": "Get all banks by user",
        "tags": [
          "Bank"
        ],
        "security": [
          {
            "AruskasAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Response after get",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Bambang": {
                    "value": {
                      "timestamp": "2022-05-31 08:12:00",
                      "status": 200,
                      "message": "",
                      "result": [
                        {
                          "id": 1,
                          "nama": "BRI",
                          "saldo": 100000
                        },
                        {
                          "id": 2,
                          "nama": "Mandiri",
                          "saldo": 500000
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create new bank",
        "tags": [
          "Bank"
        ],
        "security": [
          {
            "AruskasAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "nama",
                  "saldo"
                ],
                "properties": {
                  "nama": {
                    "type": "string"
                  },
                  "saldo": {
                    "type": "integer",
                    "minLength": 0
                  }
                }
              },
              "examples": {
                "Mandiri": {
                  "$ref": "#/components/examples/BankRequestBodyExample"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success response after create new bank",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Mandiri": {
                    "value": {
                      "timestamp": "2022-05-31 08:12:00",
                      "status": 200,
                      "message": "Berhasil membuat bank baru",
                      "result": {
                        "id": 1,
                        "nama": "Mandiri",
                        "saldo": 100000
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/banks/{id}": {
      "parameters": [
        {
          "name": "id",
          "description": "ID bank",
          "in": "path",
          "required": true,
          "schema": {
            "type": "integer"
          }
        }
      ],
      "get": {
        "summary": "Get bank by id",
        "tags": [
          "Bank"
        ],
        "security": [
          {
            "AruskasAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Mandiri": {
                    "value": {
                      "timestamp": "2022-05-31 08:12:00",
                      "status": 200,
                      "message": "",
                      "result": {
                        "id": 1,
                        "nama": "Mandiri",
                        "saldo": 100000
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "Update bank by id",
        "tags": [
          "Bank"
        ],
        "security": [
          {
            "AruskasAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "nama": {
                    "type": "string"
                  },
                  "saldo": {
                    "type": "integer"
                  }
                },
                "required": [
                  "nama",
                  "saldo"
                ]
              },
              "examples": {
                "Mandiri": {
                  "$ref": "#/components/examples/BankRequestBodyExample"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success response after update",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Mandiri": {
                    "value": {
                      "timestamp": "2022-05-31 08:12:00",
                      "status": 200,
                      "message": "Berhasil memperbarui bank",
                      "result": {
                        "id": 1,
                        "nama": "BRI",
                        "saldo": 500000
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Delete bank by id",
        "tags": [
          "Bank"
        ],
        "security": [
          {
            "AruskasAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Response after delete",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Mandiri": {
                    "value": {
                      "timestamp": "2022-05-31 08:12:00",
                      "status": 200,
                      "message": "Berhasil menghapus bank",
                      "result": []
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/saldo-bank": {
      "get": {
        "summary": "Get jumlah saldo by id",
        "tags": [
          "Bank"
        ],
        "security": [
          {
            "AruskasAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Response after get saldo bank",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Bambang": {
                    "value": {
                      "timestamp": "2022-05-31 08:12:00",
                      "status": 200,
                      "message": "",
                      "result": 800000
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/anggarans": {
      "get": {
        "summary": "Get all anggarans by user id",
        "tags": [
          "Anggaran"
        ],
        "security": [
          {
            "AruskasAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Bambang": {
                    "description": "Bambang's anggarans",
                    "value": {
                      "timestamp": "2022-05-31 23:12:00",
                      "status": 200,
                      "message": "",
                      "result": [
                        {
                          "id": 1,
                          "nama": "Makan"
                        },
                        {
                          "id": 2,
                          "nama": "Belanja"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create new anggaran",
        "tags": [
          "Anggaran"
        ],
        "security": [
          {
            "AruskasAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AnggaranRequestSchema"
              },
              "examples": {
                "Belanja": {
                  "$ref": "#/components/examples/AnggaranRequestExample"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success response after create",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Belanja": {
                    "$ref": "#/components/examples/AnggaranResponseExample"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/anggarans/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "required": true,
          "description": "Anggaran id",
          "schema": {
            "type": "integer"
          }
        }
      ],
      "get": {
        "summary": "Get anggaran by id",
        "tags": [
          "Anggaran"
        ],
        "security": [
          {
            "AruskasAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Belanja": {
                    "$ref": "#/components/examples/AnggaranResponseExample"
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "Update anggaran by id",
        "tags": [
          "Anggaran"
        ],
        "security": [
          {
            "AruskasAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AnggaranRequestSchema"
              },
              "examples": {
                "Belanja": {
                  "$ref": "#/components/examples/AnggaranRequestExample"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success response after update",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Belanja": {
                    "$ref": "#/components/examples/AnggaranResponseExample"
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Delete anggaran by id",
        "tags": [
          "Anggaran"
        ],
        "security": [
          {
            "AruskasAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Success response after delete",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Belanja": {
                    "value": {
                      "timestamp": "2022-05-31 08:12:00",
                      "status": 200,
                      "message": "Berhasil menghapus anggaran",
                      "result": []
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/histories": {
      "get": {
        "summary": "Get all histories by user",
        "tags": ["History"],
        "security": [{
          "AruskasAuth": []
        }],
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Bambang": {
                    "value": {
                      "timestamp": "2022-05-31 08:12:00",
                      "status": 200,
                      "message": "",
                      "result": [
                        {
                          "id": 1,
                          "kegiatan": "Uang masuk sebesar Rp. 1.000 ke BCA",
                          "created_at": "2022-02-07 11:41:25"
                        },
                        {
                          "id": 2,
                          "kegiatan": "Uang masuk sebesar Rp. 2.000 ke BCA",
                          "created_at": "2022-02-07 11:41:25"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/restore/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "required": true,
          "description": "History id",
          "schema": {
            "type": "integer"
          }
        }
      ],
      "post": {
        "summary": "Restore history",
        "tags": ["History"],
        "security": [{
          "AruskasAuth": []
        }],
        "responses": {
          "200": {
            "description": "Success response after restore",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Success": {
                    "value": {
                      "timestamp": "2022-05-31 08:12:00",
                      "status": 200,
                      "message": "Berhasil mengembalikan data, history sudah terhapus",
                      "result": []
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/histories/{tahun}": {
      "parameters": [
        {
          "name": "tahun",
          "in": "path",
          "required": true,
          "description": "Year of created history",
          "schema": {
            "type": "integer"
          }
        }
      ],
      "get": {
        "summary": "Get histories per month in one year",
        "tags": ["History"],
        "security": [{
          "AruskasAuth": []
        }],
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Success": {
                    "value": {
                      "timestamp": "2022-05-31 08:12:00",
                      "status": 200,
                      "message": "",
                      "result": [
                        {
                          "name": "Pemasukan",
                          "bulan": 1,
                          "value": 50000
                        },
                        {
                          "name": "Pengeluaran",
                          "bulan": 1,
                          "value": 20000
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/pemasukan": {
      "get": {
        "summary": "Get all pemasukan by user",
        "tags": ["Pemasukan"],
        "security": [{
          "AruskasAuth": []
        }],
        "parameters": [
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "description": "Limit data",
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Success": {
                    "value": {
                      "timestamp": "2022-05-31 08:12:00",
                      "status": 200,
                      "message": "",
                      "result": [
                        {
                          "id": 1,
                          "banks_id": 1,
                          "kegiatan": "Uang masuk sebesar Rp. 1.000 ke BCA",
                          "jumlah": 500000,
                          "created_at": "2022-02-07 11:41:25",
                          "restore": true
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Creat new pemasukan",
        "tags": ["Pemasukan"],
        "security": [{
          "AruskasAuth": []
        }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PemasukanRequestSchema"
              },
              "examples": {
                "Bambang": {
                  "$ref": "#/components/examples/PemasukanRequestExample"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Success": {
                    "value": {
                      "timestamp": "2022-05-31 08:12:00",
                      "status": 200,
                      "message": "Berhasil membuat pemasukan",
                      "result": []
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/pengeluaran": {
      "get": {
        "summary": "Get all pengeluaran by user",
        "tags": ["Pengeluaran"],
        "security": [{
          "AruskasAuth": []
        }],
        "parameters": [
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "description": "Limit data",
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Success": {
                    "value": {
                      "timestamp": "2022-05-31 08:12:00",
                      "status": 200,
                      "message": "",
                      "result": [
                        {
                          "id": 1,
                          "banks_id": 1,
                          "kegiatan": "Uang keluar sebesar Rp. 1.000 ke BCA",
                          "jumlah": 500000,
                          "created_at": "2022-02-07 11:41:25",
                          "restore": true
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Creat new pengeluaran",
        "tags": ["Pengeluaran"],
        "security": [{
          "AruskasAuth": []
        }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PengeluaranRequestSchema"
              },
              "examples": {
                "Bambang": {
                  "$ref": "#/components/examples/PengeluaranRequestExample"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Success": {
                    "value": {
                      "timestamp": "2022-05-31 08:12:00",
                      "status": 200,
                      "message": "Berhasil membuat pengeluaran",
                      "result": []
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/plans": {
      "get": {
        "summary": "Get all plans",
        "tags": ["Plan"],
        "security": [{
          "AruskasAuth": []
        }],
        "parameters": [
          {
            "name": "bulan",
            "in": "query",
            "required": false,
            "description": "Plan month",
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "tahun",
            "in": "query",
            "required": false,
            "description": "Plan year",
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Success": {
                    "value": {
                      "timestamp": "2022-05-31 08:12:00",
                      "status": 200,
                      "message": "",
                      "result": [
                        {
                          "id": 2,
                          "nama": "Bensin",
                          "bulan": 2,
                          "tahun": 2022,
                          "jumlah": 100000,
                          "frekuensi": 3,
                          "satuan": "Hari",
                          "total": 1000000
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create new plan",
        "tags": ["Plan"],
        "security": [{
          "AruskasAuth": []
        }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PlanRequestSchema"
              },
              "examples": {
                "Sample": {
                  "$ref": "#/components/examples/PlanRequestExample"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Success": {
                    "$ref": "#/components/examples/PlanResponseExample"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/plans/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "required": true,
          "description": "Plan id",
          "schema": {
            "type": "integer"
          }
        }
      ],
      "get": {
        "summary": "Get plan by id",
        "tags": ["Plan"],
        "security": [{
          "AruskasAuth": []
        }],
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Success": {
                    "$ref": "#/components/examples/PlanResponseExample"
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "Update plan by id",
        "tags": ["Plan"],
        "security": [{
          "AruskasAuth": []
        }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PlanRequestSchema"
              },
              "examples": {
                "Sample": {
                  "$ref": "#/components/examples/PlanRequestExample"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Success": {
                    "$ref": "#/components/examples/PlanResponseExample"
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Delete plan by id",
        "tags": ["Plan"],
        "security": [{
          "AruskasAuth": []
        }],
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Success": {
                    "value": {
                      "timestamp": "2022-05-31 08:12:00",
                      "status": 200,
                      "message": "Berhasil menghapus plan",
                      "result": []
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/users/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "required": true,
          "description": "User id",
          "schema": {
            "type": "integer"
          }
        }
      ],
      "get": {
        "summary": "Get user by id",
        "tags": ["User"],
        "security": [{
          "AruskasAuth": []
        }],
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Success": {
                    "$ref": "#/components/examples/UserResponseExample"
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "Update user by id",
        "tags": ["User"],
        "security": [{
          "AruskasAuth": []
        }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserRequestSchema"
              },
              "examples": {
                "Bambang": {
                  "$ref": "#/components/examples/UserRequestExample"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Success": {
                    "$ref": "#/components/examples/UserResponseExample"
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Delete user by id",
        "tags": ["User"],
        "security": [{
          "AruskasAuth": []
        }],
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Success": {
                    "value": {
                      "timestamp": "2022-05-31 08:12:00",
                      "status": 200,
                      "message": "Berhasil menghapus user",
                      "result": []
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/change-password/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "required": true,
          "description": "User id",
          "schema": {
            "type": "integer"
          }
        }
      ],
      "put": {
        "summary": "Change password user",
        "tags": ["User"],
        "security": [{
          "AruskasAuth": []
        }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ChangePasswordRequestSchema"
              },
              "examples": {
                "Bambang": {
                  "$ref": "#/components/examples/ChangePasswordRequestExample"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefaultResponseSchema"
                },
                "examples": {
                  "Success": {
                    "value": {
                      "timestamp": "2022-05-31 08:12:00",
                      "status": 200,
                      "message": "Berhasil memperbarui password",
                      "result": []
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "AruskasAuth": {
        "description": "Authentication for Aruskas",
        "type": "http",
        "bearerFormat": "JWT",
        "scheme": "bearer"
      }
    },
    "schemas": {
      "DefaultResponseSchema": {
        "type": "object",
        "properties": {
          "timestamp": {
            "type": "string",
            "format": "date-time"
          },
          "status": {
            "type": "integer",
            "format": "int32"
          },
          "message": {
            "type": "string"
          },
          "result": {
            "type": "object"
          }
        }
      },
      "AnggaranRequestSchema": {
        "type": "object",
        "properties": {
          "nama": {
            "type": "string"
          }
        },
        "required": [
          "nama"
        ]
      },
      "PemasukanRequestSchema": {
        "type": "object",
        "properties": {
          "pemasukan": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "jumlah": {
                  "type": "integer"
                },
                "bank": {
                  "type": "integer"
                }
              }
            }
          }
        }
      },
      "PengeluaranRequestSchema": {
        "type": "object",
        "properties": {
          "pengeluaran": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "jumlah": {
                  "type": "integer"
                },
                "bank": {
                  "type": "integer"
                },
                "anggaran": {
                  "type": "integer"
                }
              }
            }
          }
        }
      },
      "PlanRequestSchema": {
        "type": "object",
        "properties": {
          "anggarans_id": {
            "type": "integer"
          },
          "bulan": {
            "type": "integer"
          },
          "tahun": {
            "type": "integer"
          },
          "jumlah": {
            "type": "integer"
          },
          "frekuensi": {
            "type": "integer"
          },
          "satuan": {
            "type": "string"
          },
          "total": {
            "type": "integer"
          }
        }
      },
      "UserRequestSchema": {
        "type": "object",
        "properties": {
          "nama": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "pekerjaan": {
            "type": "string"
          },
          "alamat": {
            "type": "string"
          }
        },
        "required": ["nama", "email"]
      },
      "ChangePasswordRequestSchema": {
        "type": "object",
        "properties": {
          "password": {
            "type": "string"
          }
        },
        "required": ["password"]
      }
    },
    "examples": {
      "UserResponseExample": {
        "description": "User response example",
        "value": {
          "timestamp": "2022-05-31 23:12:00",
          "status": 200,
          "message": "Data saved successfully!",
          "result": {
            "id": 1,
            "nama": "Bambang",
            "email": "bambang@gmail.com",
            "pekerjaan": "Wiraswasta",
            "alamat": "Pemalang, Jawa Tengah"
          }
        }
      },
      "BankRequestBodyExample": {
        "description": "Sample bank request body",
        "value": {
          "nama": "Mandiri",
          "saldo": 100000
        }
      },
      "AnggaranRequestExample": {
        "description": "Sample anggaran request body",
        "value": {
          "nama": "Belanja"
        }
      },
      "AnggaranResponseExample": {
        "value": {
          "timestamp": "2022-05-31 23:12:00",
          "status": 200,
          "message": "...",
          "result": {
            "id": 1,
            "nama": "Belanja"
          }
        }
      },
      "PemasukanRequestExample": {
        "value": {
          "pemasukan": [
            {
              "jumlah": 100000,
              "bank": 1
            },
            {
              "jumlah": 100000,
              "bank": 2
            }
          ]
        }
      },
      "PengeluaranRequestExample": {
        "value": {
          "pengeluaran": [
            {
              "jumlah": 10000,
              "bank": 1,
              "anggaran": 1
            },
            {
              "jumlah": 10000,
              "bank": 2,
              "anggaran": 1
            }
          ]
        }
      },
      "PlanRequestExample": {
        "value": {
          "anggarans_id": 16,
          "bulan": 2,
          "tahun": 2022,
          "jumlah": 1000000,
          "frekuensi": 3,
          "satuan": "Hari",
          "total": 2000000
        }
      },
      "PlanResponseExample": {
        "value": {
          "timestamp": "2022-05-31 20:12:00",
          "status": 200,
          "message": "...",
          "result": {
            "id": 1,
            "anggarans_id": 16,
            "bulan": 2,
            "tahun": 2022,
            "jumlah": 1000000,
            "frekuensi": 3,
            "satuan": "Hari",
            "total": 2000000
          }
        }
      },
      "UserRequestExample": {
        "value": {
          "nama": "Bambang",
          "email": "bambang@gmail.com",
          "pekerjaan": "Wiraswasta",
          "alamat": "Semarang"
        }
      },
      "ChangePasswordRequestExample": {
        "value": {
          "password": "bambangnew"
        }
      }
    }
  }
}
